"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'changeme')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get('DEBUG', 0)))
# DEBUG=1

# The ALLOWED_HOSTS setting in Django is a security measure designed to prevent 
# HTTP Host header attacks. It is a list of strings representing the host/domain 
# names that a Django site can serve. 
ALLOWED_HOSTS = []
ALLOWED_HOSTS.extend(
    filter(
        None,
        os.environ.get('ALLOWED_HOSTS', '').split(','),
    )
)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Added for Dajango 5.2.8 S3 static/media file access
    'storages',
    # Main app
    'plants',
    # Image processing
    'imagekit',
    # Rich text editor
    'django_quill',
    # Calendar for selecting dates
    'django_flatpickr',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE'  : 'django.db.backends.postgresql',
        'HOST'    : os.environ.get('DB_HOST'),
        'NAME'    : os.environ.get('DB_NAME'),
        'USER'    : os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # checks the similarity between the password and a set of attributes of the user
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    # checks whether the password meets a minimum length
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        "OPTIONS": {
            "min_length": 9,
        }
    },
    # checks whether the password occurs in a list of common passwords
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    # checks whether the password isn’t entirely numeric
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'UTC'
USE_I18N      = True
USE_TZ        = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Required for AWS Lightsail to allow CSRF_TOKEN to work properly
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Determine if the container/image is running on AWS Lightsail (1) or locally (0)
# If so, setup AWS S3 storage
# It is unclear if this code is being used since whitenoise has been installed and configured

if (os.environ.get('IS_ON_AWS', '0') == '1'):
    print("DEBUG: Running on AWS Lightsail")
    #############################################################################
    # AWS/S3 setup for serving static and media files when using Django 5.2.8   #
    #############################################################################

    # AWS S3 Settings
    AWS_ACCESS_KEY_ID       = os.environ.get('AWS_S3_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY   = os.environ.get('AWS_S3_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME      = 'us-east-1'
    AWS_S3_CUSTOM_DOMAIN    = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'

    # Optional: Control ACLs and query string authentication
    AWS_DEFAULT_ACL         = 'public-read'
    AWS_QUERYSTRING_AUTH    = False

    # Storage backends for Django 4.2+
    STORAGES = {
        "default": {
            "BACKEND": "app.storage_backends.PublicMediaStorage",
            # Options can be passed here if not defined in the class
        },
        "staticfiles": {
            "BACKEND": "app.storage_backends.StaticStorage",
            # Options can be passed here if not defined in the class
        }
    }

    # STATIC_URL is a crucial setting that defines the URL prefix for accessing static files 
    # (like CSS, JavaScript, and images) in your project. It specifies the base URL from 
    # which these files will be served to the client's browser.
    #
    # STATIC_ROOT is a setting that defines the absolute file system path to a directory 
    # where all static files (CSS, JavaScript, images, etc.) from your Django project and
    # its installed apps will be collected during deployment.
    #
    # STATICFILES_DIRS in is a setting used to specify additional directories where Django's 
    # collectstatic command should look for static files, beyond the default static/ directories
    # found within each installed app

    STATIC_URL         = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
    STATIC_ROOT        = os.path.join(BASE_DIR, 'staticfiles')
    # STATICFILES_DIRS = [   ]

    # MEDIA_URL defines the base URL from which your Django application serves user-uploaded files. 
    # This means that when a user uploads an image or a file, the URL used to access that file in a 
    # web browser will start with the value defined in MEDIA_URL

    MEDIA_URL  = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
    #############################################################################
else:
    #############################################################################
    # Setup for serving static and media files in local development environment #
    #############################################################################
    print("DEBUG: Running in local development environment")
    # STATIC_URL defines the URL prefix used to access static files in your templates
    STATIC_URL   = '/static/'
    STATIC_ROOT  = '/app/static/'
    # MEDIA_URL defines the URL prefix used to access media files in your templates
    MEDIA_URL    = '/media/'
    MEDIA_ROOT   = '/app/media/'
    #############################################################################

# Directs user to login page when login is required
# AR: Login redirection should be fixed
LOGIN_REDIRECT_URL  = "/plants/index"
LOGOUT_REDIRECT_URL = "/plants/index"

# Global settings for all django_flatpickr inputs
DJANGO_FLATPICKR = {
    # Name of the theme to use - https://flatpickr.js.org/themes/
    "theme_name": "dark",
}

# Quill Rich Text Editor configuration
QUILL_CONFIGS = {
    'default':{
        'theme': 'snow',
        'modules': {
            'syntax': True,
            'toolbar': [
                [
                    {'font': []},
                    {'header': []},
                    {'align': []},
                    'bold', 
                    'italic', 
                    'underline', 
                    'strike', 
                    'blockquote',
                    { 'indent': '-1'}, 
                    { 'indent': '+1' },
                    {'list': 'ordered'},
                    {'list': 'bullet' },
                    {'color': []},
                    {'background': []},
                ],
                ['clean'],
            ]
        }
    }
}