# Generated by Django 4.1.5 on 2024-12-02 16:12

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='tbd', max_length=64)),
                ('city', models.CharField(blank=True, default='tbd', max_length=32)),
                ('state', models.CharField(blank=True, default='tbd', max_length=16)),
                ('owner', models.CharField(blank=True, default='tbd', max_length=64)),
                ('usda_zone', models.CharField(blank=True, default='tbd', max_length=16)),
                ('sunset_zone', models.CharField(blank=True, default='tbd', max_length=32)),
                ('question', models.CharField(blank=True, default='No', max_length=8)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('caption_1', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('caption_2', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('caption_3', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('caption_4', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('caption_5', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('caption_6', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('caption_7', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('caption_8', models.CharField(blank=True, default='tbd', max_length=64)),
                ('slug', models.SlugField(default='tbd')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonName', models.CharField(max_length=255)),
                ('type_x', models.CharField(blank=True, default='tbd', max_length=32)),
                ('bloom_color', models.CharField(blank=True, default='tbd', max_length=128)),
                ('bloom_season', models.CharField(blank=True, default='tbd', max_length=64)),
                ('height_feet', models.IntegerField(blank=True, default=0, null=True)),
                ('height_inch', models.IntegerField(blank=True, default=0, null=True)),
                ('width_feet', models.IntegerField(blank=True, default=0, null=True)),
                ('width_inch', models.IntegerField(blank=True, default=0, null=True)),
                ('sun_exposure', models.CharField(blank=True, default='tbd', max_length=64)),
                ('water_rqmts', models.CharField(blank=True, default='tbd', max_length=32)),
                ('pollinators', models.CharField(blank=True, default='tbd', max_length=64)),
                ('ca_native', models.CharField(blank=True, default='tbd', max_length=8)),
                ('usda_zone_min', models.CharField(blank=True, default='tbd', max_length=16)),
                ('usda_zone_max', models.CharField(blank=True, default='tbd', max_length=16)),
                ('sunset_zones', models.CharField(blank=True, default='tbd', max_length=32)),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('pruning', django_quill.fields.QuillField(blank=True, null=True)),
                ('fertilization', django_quill.fields.QuillField(blank=True, null=True)),
                ('kingdom', models.CharField(blank=True, default='tbd', max_length=64)),
                ('division', models.CharField(blank=True, default='tbd', max_length=64)),
                ('class_x', models.CharField(blank=True, default='tbd', max_length=64)),
                ('order', models.CharField(blank=True, default='tbd', max_length=64)),
                ('family', models.CharField(blank=True, default='tbd', max_length=64)),
                ('genus', models.CharField(blank=True, default='tbd', max_length=64)),
                ('species', models.CharField(blank=True, default='tbd', max_length=64)),
                ('variety', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('caption_1', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('caption_2', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('caption_3', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('caption_4', models.CharField(blank=True, default='tbd', max_length=64)),
                ('creator', models.CharField(blank=True, default='tbd', max_length=64)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('plant_show', models.CharField(blank=True, default='No', max_length=8)),
                ('slug', models.SlugField(default='')),
                ('gardens', models.ManyToManyField(blank=True, to='plants.garden')),
            ],
        ),
        migrations.CreateModel(
            name='MyPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(blank=True, default='tbd', max_length=64)),
                ('sun_exposure', models.CharField(blank=True, default='tbd', max_length=64)),
                ('slug', models.SlugField(default='tbd')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.garden')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='tbd', max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, default='tbd', max_length=64)),
                ('comment', django_quill.fields.QuillField(blank=True, null=True)),
                ('slug', models.SlugField(default='')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
    ]
