# Generated by Django 4.1.5 on 2024-12-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='pH_max',
            field=models.CharField(blank=True, default='tbd', max_length=16),
        ),
        migrations.AddField(
            model_name='plant',
            name='pH_min',
            field=models.CharField(blank=True, default='tbd', max_length=16),
        ),
    ]
