# Generated by Django 4.1.5 on 2024-12-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_ph_max_plant_ph_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='ucd_all_star',
            field=models.CharField(blank=True, default='tbd', max_length=8),
        ),
    ]
