# Generated by Django 4.1.5 on 2024-12-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_ucd_all_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='water_rqmts',
            field=models.CharField(blank=True, default='tbd', max_length=64),
        ),
    ]
