# Generated by Django 4.1.5 on 2024-12-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_plant_water_rqmts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='usda_zone_max',
            field=models.CharField(blank=True, default='tbd', max_length=32),
        ),
        migrations.AlterField(
            model_name='plant',
            name='usda_zone_min',
            field=models.CharField(blank=True, default='tbd', max_length=32),
        ),
    ]
