# Generated by Django 4.1.5 on 2024-12-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_plant_usda_zone_max_alter_plant_usda_zone_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplant',
            name='owner',
            field=models.CharField(blank=True, default='tbd', max_length=64),
        ),
    ]
