# Generated by Django 4.1.5 on 2024-12-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_myplant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='myplant',
            name='pH',
            field=models.CharField(blank=True, default='tbd', max_length=16),
        ),
        migrations.AddField(
            model_name='myplant',
            name='soil_type',
            field=models.CharField(blank=True, default='tbd', max_length=16),
        ),
        migrations.AlterField(
            model_name='myplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
        ),
    ]
