# Generated by Django 5.2.8 on 2026-08-06 00:13

import django_uuid_upload
import functools
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0004_delete_pest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_name', models.CharField(max_length=32)),
                ('pest_type', models.CharField(blank=True, default='tbd', max_length=32)),
                ('pest_url', models.URLField(blank=True, default='tbd')),
                ('image_1', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(django_uuid_upload._upload_to_uuid_impl, *(), **{'make_dir': False, 'path': 'images/', 'remove_qs': True}))),
                ('caption_1', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_2', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(django_uuid_upload._upload_to_uuid_impl, *(), **{'make_dir': False, 'path': 'images/', 'remove_qs': True}))),
                ('caption_2', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_3', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(django_uuid_upload._upload_to_uuid_impl, *(), **{'make_dir': False, 'path': 'images/', 'remove_qs': True}))),
                ('caption_3', models.CharField(blank=True, default='tbd', max_length=64)),
                ('image_4', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(django_uuid_upload._upload_to_uuid_impl, *(), **{'make_dir': False, 'path': 'images/', 'remove_qs': True}))),
                ('caption_4', models.CharField(blank=True, default='tbd', max_length=64)),
                ('pest_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(django_uuid_upload._upload_to_uuid_impl, *(), **{'make_dir': False, 'path': 'images/', 'remove_qs': True}))),
                ('plants', models.ManyToManyField(to='plants.plant')),
            ],
        ),
    ]
