# Generated by Django 5.2.8 on 2026-08-06 00:51

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pest',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pest',
            name='management',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
