# Generated by Django 5.2.8 on 2026-08-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pests', '0002_pest_description_pest_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pest',
            name='pest_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
