# Generated by Django 5.2.8 on 2026-08-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pests', '0003_alter_pest_pest_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pest',
            name='genus',
            field=models.CharField(blank=True, default='tbd', max_length=64),
        ),
        migrations.AddField(
            model_name='pest',
            name='species',
            field=models.CharField(blank=True, default='tbd', max_length=64),
        ),
    ]
