# Generated by Django 5.2.8 on 2026-08-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pests', '0004_pest_genus_pest_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='pest',
            name='family',
            field=models.CharField(blank=True, default='tbd', max_length=64),
        ),
        migrations.AddField(
            model_name='pest',
            name='life_cycle',
            field=models.CharField(blank=True, default='tbd', max_length=32),
        ),
    ]
